M48
; DRILL file {KiCad 8.0.7} date 2025-02-13T13:50:41+0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-13T13:50:41+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X5.2009Y-2.8819
X5.2009Y-3.1094
T2
X5.0004Y-3.5201
X5.0004Y-3.587
M30
