M48
; DRILL file {KiCad 7.0.9} date 2023年12月01日 星期五 13时28分02秒
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-01T13:28:02+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X4.2327Y-2.8834
X4.2327Y-3.111
T2
X4.0161Y-3.5461
X4.0161Y-3.613
T0
M30
